#! /bin/zsh

setopt ALL_EXPORT
# editor
EDITOR=vi
VISUAL=vi

# color setup for ls

eval $(dircolors -b)

# python env
PYTHONPATH=.
VIRTUALENV_USE_DISTRIBUTE=1
DF_LOG_DIR=~/tmp

# TERM
TERM=xterm-256color 
ZSH_THEME_TERM_TITLE_IDLE="%~ (%n@%m)" 

# node/nave

NAVE_DIR=/home/bwang/.nave
NAVE_SRC=$NAVE_DIR/src
NAVE_ROOT=$NAVE_DIR/installed
#NAVEVERSION=0.6.6
#NAVE=0.6.6-default
NAVENAME=default
PATH=$NAVE_ROOT/$NAVENAME/bin:/opt/vagrant/bin:$PATH
NODE_PATH=$NAVE_ROOT/$NAVENAME/lib/node_modules:$NAVE_ROOT/$NAVENAME/lib/node
#NAVELVL=1

#jsctags
NODE_PATH=$NODE_PATH:/usr/local/lib/jsctags/
unsetopt ALL_EXPORT
# vi:ft=zsh
