#! /bin/zsh

setopt ALL_EXPORT
# editor
EDITOR=vim
VISUAL=vim

# color setup for ls

#eval $(dircolors -b)

# python env
PYTHONPATH=.
VIRTUALENV_USE_DISTRIBUTE=1

# TERM
TERM=${TERM:-xterm-256color}

# node


NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

PATH=$HOME/bin:/usr/local/bin:/usr/local/sbin:$PATH


# aws cli
AWS_DEFAULT_REGION=ap-southeast-2

# Golang
GOPATH=/Users/bruce/go
PATH=$PATH:$GOPATH/bin

unsetopt ALL_EXPORT
# vi:ft=zsh
